export const OPEN_SERVICE_REQUEST_STATUSES = ["queued", "created", "assigned"];

export const SERVICE_REQUEST_STATUS = {
  assigned: "Assigned to responsible person",
  queued: "Submitted",
  created: "Submitted",
  completed: "Completed",
};

export const TASK_TYPES = [
  "Roads",
  "Sewerage",
  "Street Trees",
  "Pavement: Pavement Damage",
  "Finance General",
  "Masakhane",
  "Supply Chain and Fleet",
  "Finance: Accounts and Services",
  "Electricity: Faults",
  "Water Complaints",
  "Manhole: Damage or Missing",
  "Street Signs: Sign damage or missing",
  "Municipal Property",
  "Street Lighting: Lights on Permanently",
  "Street Lighting: Lights not working/Damaged",
  "Refuse: Dumped Rubbish",
  "Pavements: Weeds and grass cutting",
  "Refuse: Collection and Landfil Sites",
  "Road Markings",
  "Town Planning (Rezoning and Illegal Land Use)",
  "Public Participation and Ward Committees",
  "Communication",
  "Human Resources",
  "Fraud and Corruption",
  "Property Administration",
  "Tourism and Econom ic Development",
  "Housing: Illegal Structures",
  "Housing Complaints",
  "Thusong Centre and Social Development",
  "Resorts",
  "Libraries",
  "Traffic, Law Enforcement and Animal Control",
  "Private Erven",
  "Cemetery",
  "Parks and Open Spaces",
  "Building Complaint",
  "Air Quality and Noise Complaint",
];

export const SUPPORT_EMAIL="cape-agulhas-app@openup.org.za"
